---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---
```{r}
library(MASS)
library(ISLR)
library(tidyr)
library(dplyr)
library(readr)
library(ggplot2)
library(corrplot)
library(viridis)
library(WVPlots)
```

```{r}

consolidated_data <- read_csv("consolidated_data.csv")
head(consolidated_data)
```
```{r}
# Calibration of Current (not used in project)
df_cal <- consolidated_data %>%
  dplyr::select(current_raw, temp, das_temp, voltage, flux, current_cal)%>%
  filter(current_raw > -1, voltage < 0.9, current_raw < 0.9)%>%
  mutate(dt = das_temp)%>%
  mutate(dI = -current_raw)

df_cal_cor <- df_cal%>%
  cor()
  

cal_fit = lm(dI ~ dt, df_cal)
plot(cal_fit)
plot(df_cal$dt, df_cal$dI)
summary(cal_fit)
b = cal_fit[["coefficients"]][["(Intercept)"]]
m = cal_fit[["coefficients"]][["dt"]]
plot(df_cal$current_raw + df_cal$dt*m + b)
plot(df_cal$current_cal)
sd(df_cal$current_raw + df_cal$dt*m + b)
consolidated_data <- consolidated_data%>%
  mutate(current_cal2 = consolidated_data$current_raw + (consolidated_data$das_temp*m + b))%>%
  mutate(power2 = current_cal2*voltage)
xmin = 17200
xmax = 19500
plot(consolidated_data$current_cal2[xmin:xmax])
plot(consolidated_data$current_cal[xmin:xmax])
plot(consolidated_data$current_raw[xmin:xmax])
```

```{r}
result <- consolidated_data %>%
  dplyr::select(current_raw, current_cal, voltage, flux, temp, in_rate, out_rate, power, in_rate, out_rate, pump_voltage, vdrop, pump_power, power_loss, 'W/m^2 Solar Radiation') %>%
  na.omit %>%
  cor()%>%
  corrplot(method="circle", order='hclust')
result

eda <- consolidated_data %>%
  dplyr::select(current_raw, current_cal, voltage, flux, temp, in_rate, out_rate, in_rate, out_rate)%>%
  filter(current_cal > -1, flux > 0, voltage > 0, flux < 720)

plot(eda)
```



```{r}
# Power Loss in wire versus power generated
dfpv <- consolidated_data%>%
  select(current_cal, voltage, flux, temp, in_rate)%>%
  filter(flux < 710, in_rate > 0)

outliers <- which(dfpv$current_cal < 0)
dfpv$current_cal[outliers] <- 0
ggplot(dfpv, aes(voltage, current_cal, col=flux)) + geom_point() + scale_color_viridis()
```
```{r}
# This chunck makes a model for the pump curve. We did not use this for the project since it produced bad results.
df_pump <- consolidated_data%>%
  select(current_cal, voltage, flux, temp, in_rate, pump_power, power, power_loss)%>%
  filter(pump_power > 20 & in_rate > 0 & in_rate < 14)

ggplot(df_pump, aes(pump_power, in_rate, col=temp)) + geom_point() + scale_color_viridis() + stat_smooth(method='lm', formula=y~poly(x, 3))
ggplot(df_pump,aes(x=power, y=in_rate )) + geom_point(size=0.25) + geom_density_2d() + labs(x="Power", y="Pump Rate", title="Pump Curve") +  theme(plot.title = element_text(hjust = 0.5)) + stat_smooth(method='lm', formula=y~poly(x, 3))
pump_curve_model = lm(df_pump$in_rate~poly(df_pump$pump_power, 3))
summary(pump_curve_model)
plot(pump_curve_model)
```

```{r}
hist(power_loss, breaks = 40000, xlim=c(0, 160), ylim=c(0, 150))
```
```{r}
plot(power, power_loss, ylim=c(0, 160))
```

```{r}
plot(power, pump_power, ylim=c(-100, 1300))
fit = lm(pump_power~power + I(power^(1/2)))
summary(fit)


mean(pump_power/power, na.rm = TRUE)
```
```{r}
dfp <- consolidated_data%>%
  select(current_cal, voltage, vdrop, flux, temp, power, pump_power, in_rate, power_loss)%>%
  filter(current_cal > 0)

outliers <- which(dfp$current_cal < -1)
dfp$current_cal[outliers] <- 0


plot(dfp$power, dfp$power_loss)
fit = lm(dfp$pump_power~dfp$power+0)
summary(fit)

mean(dfp$pump_power/dfp$power, na.rm = TRUE)
mean(dfp$power, na.rm = TRUE)
mean(dfp$pump_power, na.rm = TRUE)

# Create the function.
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}
getmode(dfp$power)
getmode(dfp$pump_power)
```

```{r}
# Data fit for pump curve. Creates equation used for project.
df_flow <- consolidated_data%>%
  select(current_cal, voltage, vdrop, flux, temp, power, pump_power, in_rate)%>%
  filter(pump_power>30 & in_rate > 0 & in_rate < 14)
plot(df_flow$pump_power, df_flow$in_rate)

pumpfit = lm(in_rate ~ pump_power + I(pump_power^(1/2)), data=df_flow)
plot(pumpfit)
summary(pumpfit)
# -5.2733237 + -0.0066150(pump_power) + 0.6990381(pump_power)^(1/2)
```

Figure out the total daily use of water.
```{r}
water <- consolidated_data %>% 
  separate(time, c("date", "min"), sep = " ") %>%
  group_by(date) %>%
  mutate(sum_water_out = sum(out_rate, na.rm = TRUE)) %>%
  mutate(sum_water_in = sum(in_rate, na.rm = TRUE)) %>%
  filter(date < as.Date("2019-07-12")) %>%
  filter(date > as.Date("2019-06-27"))
```
```{r}
#plot(water$date, water$sum_water_in)
ggplot(data = water, aes(x = date, y = sum_water_out)) +
  geom_point() +
  labs(x = "Date",
    y = "Water Used (gal)",
    title = "Amount of Water Used per Day") + theme(axis.text.x = element_text(angle = 45))

wawa <- water %>%
  select(temp, flux, sum_water_in, sum_water_out, date) %>%
  na.omit()

ggplot(wawa,) + 
  geom_segment(aes(x=date, xend=date, yend=sum_water_out, y=0), color='cyan4', size=4) + 
  geom_segment(aes(x=date, xend=date, yend=sum_water_in, y=sum_water_out), color='dark green', size=4) + 
  geom_point(aes(x=date, y=sum_water_in, color='Water Pumped'), size=3) + 
  geom_point(aes(x=date, y=sum_water_out, color="Water Used"), size=3) + 
  theme(axis.text.x = element_text(angle = 45)) + 
  labs(x = "Date", y = "Water Volume (gal)", title = "Water Pumped and Water Used Each Day") + 
  theme(plot.title = element_text(hjust = 0.5), legend.justification = 'right') + theme(legend.title = element_blank())
```
```{r}
hist(wawa$sum_water_in)
hist(wawa$sum_water_out)
```
Power vs Solar Irradiation
```{r}
pow_lux <- water %>%
  select(flux, power, temp, in_rate) %>%
  filter(flux < 718 & flux > 0 & power > 30 & in_rate > 0)

lem <- lm(power ~ flux, data = pow_lux)
summary(lem)

intercept = lem[["coefficients"]][["(Intercept)"]]
slope = lem[["coefficients"]][["flux"]]

ggplot(pow_lux,) + 
  geom_point(aes(flux, power), size=0.25, alpha=0.3) + 
  labs(x = "Flux (W/m^2)", y = "Power (W)", title = "Solar Power Generation w/ Pump Running") + theme(plot.title = element_text(hjust = 0.5)) + 
  geom_abline(slope = lem$coefficients[2], intercept = lem$coefficients[1]) + 
  geom_text(aes(200, 750, label = paste("y =",slope, "x", " + ", intercept))) +
  theme(axis.text.x = element_text(angle = 45))

plot(lem)
```
```{r}
#https://winvector.github.io/WVPlots/reference/ScatterHist.html

set.seed(34903490)
y = water$in_rate
x = water$flux
frm = data.frame(x=x,y=y)
WVPlots::ScatterHist(frm, "x", "y",
  title= "Example Fit",
  smoothmethod = "lm",
  contour = TRUE)
######

#plot(consolidated_data$time, 
     #consolidated_data$in_rate, col = "green")
#lines(consolidated_data$time,
      #consolidated_data$out_rate, col = "red")
```


